


services:
  db:
    image: mysql:8.0
    container_name: diagramator_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diagramator_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: diagramator_backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diagramator_frontend
    restart: unless-stopped
    ports:
      - "3007:3000"
    environment:
      - WDS_SOCKET_PORT=3007
      - FAST_REFRESH=false
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:

